[package]
name = "lcms2-sys"
authors = ["Kornel Lesiński <kornel@geekhood.net>"]
build = "src/build.rs"
links = "lcms2"
repository="https://github.com/pornel/rust-lcms2-sys.git"
include = ["src/**/*", "Cargo.toml", "README.md"]
description = "Bindings for liblcms2 (Little CMS)"
readme = "README.md"
license = "MIT"
keywords = ["icc", "color", "profile", "lcms", "sys"]
categories = ["multimedia::images", "external-ffi-bindings" ]
version = "2.2.0"

[lib]
doctest = false

[dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3"
