[package]
name = "lcms2-sys"
version = "0.1.0"
authors = ["Kornel Lesiński <kornel@geekhood.net>"]
build = "src/build.rs"
repository="https://github.com/pornel/rust-lcms2-sys.git"

[dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3"
