[package]
name = "lcms2-sys"
version = "0.5.0"
authors = ["Kornel Lesiński <kornel@geekhood.net>"]
build = "src/build.rs"
repository="https://github.com/pornel/rust-lcms2-sys.git"
include = ["src/**/*", "Cargo.toml", "README.md"]
description = "Bindings for liblcms2 (Little CMS)"
readme = "README.md"
license = "MIT"
keywords = ["icc", "color", "profile", "lcms", "sys"]

[lib]
doctest = false

[dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3"
